#!/usr/bin/env python3
"""Build the compound-21/47 PGK2 pocket-graph ensemble."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from logica_binding.graph_model import build_pocket_graph


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pocket-json",
        type=Path,
        default=ROOT / "artifacts" / "pgk2_inhibitor_pocket" / "inhibitor_pocket.json",
    )
    parser.add_argument(
        "--cmp21-pdb",
        type=Path,
        default=ROOT / "artifacts" / "pgk2_structural_pilot" / "PGK2_cmp21_1.pdb",
    )
    parser.add_argument(
        "--cmp47-pdb",
        type=Path,
        default=ROOT / "artifacts" / "pgk2_structural_pilot" / "PGK2_cmp47_1.pdb",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "artifacts" / "graph_logica" / "pocket_graphs",
    )
    parser.add_argument("--chain", default="A")
    parser.add_argument("--spatial-cutoff", type=float, default=10.0)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    for path in (args.pocket_json, args.cmp21_pdb, args.cmp47_pdb):
        if not path.exists():
            raise FileNotFoundError(path)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    report: dict[str, object] = {
        "definition": "PGK2 inhibitor-pocket graph ensemble for Graph LogiCA",
        "direct_contact_policy": (
            "Only the 6-A union around crystallographic compounds 21/47 may receive "
            "ligand-protein edges; the 10-A shell supplies protein context."
        ),
        "templates": [],
    }
    for label, path in (("cmp21", args.cmp21_pdb), ("cmp47", args.cmp47_pdb)):
        graph = build_pocket_graph(
            path,
            args.pocket_json,
            chain=args.chain,
            spatial_cutoff=args.spatial_cutoff,
        )
        output = args.output_dir / f"{label}_chain_{args.chain}.pt"
        torch.save(graph, output)
        report["templates"].append(
            {
                "label": label,
                "source": str(path),
                "graph": str(output),
                "nodes": int(graph.node_features.shape[0]),
                "direct_pocket_nodes": int(graph.direct_mask.sum()),
                "directed_protein_edges": int(graph.edge_index.shape[1]),
            }
        )
    report["limitations"] = [
        "These files contain protein-template graphs only.",
        "A candidate needs a pose in the matching template frame before protein-ligand contact edges can be constructed.",
        "No challenge validation or test submission is generated by this script.",
    ]
    report_path = args.output_dir / "report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
